### ISSUE TITLE
Translate to Russian

### ISSUE THREAD

**Issue by Capster** [Capster/node-shikimori#10]
Писал README.md по привычке на английском, но думаю, что поскольку аудитория в основном русскоязычная, стоит сделать перевод в виде README.ru.md файла. Если кто-нибудь напишет перевод — буду очень благодарен.

**Comment by Dmitryitis** [comment]
Привет, могу помочь с этим

**Comment by Dmitryitis** [comment]
@Capster, PR готов https://github.com/Capster/node-shikimori/pull/20
