### ISSUE TITLE
Readme.md содержит неправильное описание функции auth

### ISSUE THREAD

**Issue by airyng** [Capster/node-shikimori#11]
Указано:
```
const { getAccessToken } = auth({
            client_id: 'YOUR_CLIENT_ID',
            client_secret: 'YOUR_CLIENT_SECRET'
})
```
Но запуск такой функции генерирует не верный запрос, потому как исходный код содержит другие имена полей. Сигнатура вызова такая:
```
const { getAccessToken } = auth({
            client_id: 'YOUR_CLIENT_ID',
            client_secret: 'YOUR_CLIENT_SECRET'
})
```

**Comment by Capster** [comment]
Привет,

Спасибо, что указал на ошибку. Случайно переписал snake_case'ом как в Rust'е.
Если найдешь еще какие-нибудь проблемы с документацией или баги, буду рад новым issue.
