### ISSUE TITLE
Can't send update request to change user_rates

### ISSUE THREAD

**Issue by airyng** [Capster/node-shikimori#15]
Some details was changed in patch method of UserRate requests.
Now we should send data about changes in Body  of HTTP Request.

As example here is my real request from shikimori.one site:
![image](https://github.com/Capster/node-shikimori/assets/14352077/a567a03d-a85a-4557-8c9a-8e936283ddcb)

Unfortunately I didn't find the info about this changes. And also unfortunately I didn't realize how exactly I should change it via TypeScript.
So I have to ask you to fix it by yourself.

In vanilla JS I managed to fix it with that code:
![image](https://github.com/Capster/node-shikimori/assets/14352077/7049b993-e0ef-4f7b-961e-174841a9ef4f)
![image](https://github.com/Capster/node-shikimori/assets/14352077/ac2de31e-0f96-4aa9-a661-2696e6ee85d9)

**Comment by Capster** [comment]
Alright, I'll look into it

**Comment by airyng** [comment]
@Capster, I've noticed that the similar issue with POST method request. Please, pay attention to this too.

**Comment by Capster** [comment]
PR #11 seems to have fixed the issue. Feel free to reopen the issue if you encounter any related bugs. Thanks!
